project:
  type: website
  output-dir: docs

website:
  title: "Faculty Enrichment Program in Applied Malaria Modeling"
  reader-mode: true
  favicon: numalaria_logo.png
  sidebar: 
    style: "floating"    
    title: "Faculty Enrichment Program in Applied Malaria Modeling"
    logo: numalaria_logo.png
    background: light
    foreground: dark
    collapse-level: 1
    search: true
    contents:
      - section: "2023 Program"
        contents: 
          - text: Example Exercises
            href: https://github.com/numalariamodeling/FE-2023-examples
          - program/program_resources/program_faq.qmd
          - resources/articles/journal_club.qmd
          - program/program_resources/program_materials.qmd
          - program/program_resources/session_recordings.qmd
      - section: "EMOD How-To Guides"
        contents: guides/*.qmd
      - section: "Other Resources"            
        contents: resources/*.qmd
    tools: 
      - icon: github
        menu: 
          - text: Website Source Code
            url: https://github.com/numalariamodeling/FE-2023-quarto-website
          - text: Example Exercises
            url: https://github.com/numalariamodeling/FE-2023-examples
  page-footer:
    right: 
      - text: <a href="https://www.numalariamodeling.org/"> © NU Malaria Modeling 2023
format:
  html:
    theme: pulse
    css: styles.css
    toc: true

editor: source

