project:
  type: website
  output-dir: docs


website:
  title: "Faculty Enrichment Program in Applied Malaria Modeling"
  navbar:
    search: true
    left:
      - text: "Info"
        menu: 
          - curriculum.qmd
          - curriculum/program_resources/program_faq.qmd
          - curriculum/program_resources/program_handbook.qmd
          - curriculum/program_resources/example_exercises.qmd
          - curriculum/program_resources/session_recordings.qmd
      - text: "Resources"
        menu:
          - resources.qmd
          - resources/articles.qmd
          - resources/coding_resources.qmd
          - resources/science_communication.qmd
      - text: "2023 Program"
        menu:
          - guides.qmd
          - resources/articles/journal_club.qmd
          - curriculum/Program Materials.qmd
  page-footer:
    center: 
      - text: "© NU Malaria Modeling 2023."

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: source

