project:
  type: website
  output-dir: docs


website:
  title: "Faculty<br>Enrichment<br>Program<br>in<br>Applied<br>Malaria<br>Modeling"
  sidebar:
    collapse-level: 1
    background: primary
    search: true
    contents:
      - section: "Program Info"
        contents: 
          - text: Example Exercises
            href: https://github.com/numalariamodeling/FE-2023-examples
          - curriculum/program_resources/program_faq.qmd
          - resources/articles/journal_club.qmd
          - curriculum/program_resources/program_handbook.qmd
          - curriculum/program_resources/session_recordings.qmd

      - section: "EMOD How-To Guides"
        contents: guides/*.qmd
      - section: "Other Resources"            
        contents: resources/*.qmd
    tools: 
      - icon: github
        menu: 
          - text: Website Source Code
            url: https://github.com/numalariamodeling/FE-2023-quarto-website
          - text: Example Exercises
            url: https://github.com/numalariamodeling/FE-2023-examples
  page-footer:
    right: 
      - text: <a href="https://www.numalariamodeling.org/"> © NU Malaria Modeling 2023
format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: source

