project:
  type: website
  output-dir: docs
  
execute: 
  freeze: auto

website:
  title: "2023 Faculty Enrichment Program in Applied Malaria Modeling"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: About
      - resources.qmd
      - people.qmd
      - guides.qmd

format:
  html:
    theme: pulse
    css: styles.css
    toc: true

editor: source

