project:
  type: website
  
execute:
  freeze: auto

website:
  title: "2023 Faculty Enrichment Program in Applied Malaria Modeling"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: About
      - help.qmd
      - resources.qmd
      - people.qmd

format:
  html:
    theme: pulse
    css: styles.css
    toc: true

editor: visual

